[project]
name = "nmpc_multirotor"
version = "1.0.0"

dependencies = [
    "numpy>=1.21.2,<3.0.0",
    "numpy-stl>=3.0.1,<4.0.0",
    "scipy>=1.5.2,<2.0.0",
    "pygame>=2.5.0,<3.0.0",
    "PyOpenGL>=3.1.7,<4.0.0",
    "casadi==3.7.0",
]

[tool.black]
line-length = 100

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
